name: Build and Release LaTeXCV

on:
  push:
    tags:
      - 'v*'       # runs on version tags like v0.1.0
  pull_request:
    branches:
      - master       # optional: run on PRs to main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Build wheel with uv
        run: |
          uv build

      - name: Build Linux executable with PyInstaller
        run: |
          uv pip install pyinstaller
          pyinstaller --onefile src/latexcv/main.py --name latexcv

      - name: List artifacts
        run: ls -l dist
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: latexcv-linux-wheel
          path: dist/*.whl
      - name: Upload Linux executable
        uses: actions/upload-artifact@v3
        with:
          name: latexcv-linux
          path: dist/latexcv

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install pyinstaller

      - name: Build Windows exe
        run: pyinstaller --onefile src/latexcv/main.py --name latexcv

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: latexcv-windows
          path: dist/latexcv.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install pyinstaller

      - name: Build macOS executable
        run: pyinstaller --onefile src/latexcv/main.py --name latexcv

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: latexcv-macos
          path: dist/latexcv

